version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    # TF_VERSION: "1.3.7"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "yum clean all"
      - "yum makecache fast"
      - "yum install -y yum-utils"
      - "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo"
      - "yum -y install terraform --nogpgcheck"
      - "yum -y install python-chardet --nogpgcheck --skip-broken --disableplugin=fastestmirror"

  build:
    commands:
      - "cd ${CODEBUILD_SRC_DIR}"
      - "terraform plan"
      - "echo ## TERRAFORM APPLY : Starting with the Terraform Apply"
      - "terraform apply --auto-approve"
      #- "terraform apply -input=false tfapply"

artifacts:
  files:
    - '**/*'
